<?php

namespace AppBundle\Repository;

/**
 * AgentAdministratifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgentAdministratifRepository extends \Doctrine\ORM\EntityRepository
{
}
