<?php

namespace AppBundle\Repository;

/**
 * EtageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtageRepository extends \Doctrine\ORM\EntityRepository
{
}
