app:
    resource: '@AppBundle/Controller/'
    type: annotation

professeur_registration:
    path:  /register/professeur
    defaults: { _controller: AppBundle:RegistrationProfesseur:register }

etudiant_registration:
    path:  /register/etudiant
    defaults: { _controller: AppBundle:RegistrationEtudiant:register }

agent_administratif_registration:
    path:  /register/agent-administratif
    defaults: { _controller: AppBundle:RegistrationAgentAdministratif:register }

salle_add:
    path:  /salle/add
    defaults: { _controller: AppBundle:Salle:add }

etage_add:
    path: /etage/add
    defaults: { _controller: AppBundle:Etage:add }

batiment_add:
    path: /batiment/add
    defaults: { _controller: AppBundle:Batiment:add }

reservation_add:
    path: /reservation/add
    defaults: { _controller: AppBundle:Reservation:add }

fos_user_security_login:
    path: /login
    defaults: { _controller: AppBundle:Security:login }

fos_user_security_check:
    path: /login_check
    defaults: { _controller: FOSUserBundle:Security:check }

fos_user_security_logout:
    path: /logout
    defaults: { _controller: FOSUserBundle:Security:logout }

fos_user_registration_confirmed:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /confirmed

#fos_user_security:
 #   resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

#fos_user_registration_register:
 #   resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
  #  prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"

calendrier:
    path: /calendrier
    defaults: { _controller: AppBundle:CalendarEvent:load }
    methods: [GET, POST]

appBundle_resize:
    path:     /calendrier/resize
    defaults: { _controller: AppBundle:CalendarEvent:resizeEvent }
    methods:  [GET, POST]

appBundle_drop:
    path:     /calendrier/drop
    defaults: { _controller: AppBundle:CalendarEvent:dropEvent }
    methods:  [GET, POST]

appBundle_delete:
    path:     /calendrier/delete
    defaults: { _controller: AppBundle:CalendarEvent:deleteEvent }
    methods:  [GET, POST]

appBundle_editEvent:
    path:     /calendrier/edit/title
    defaults: { _controller: AppBundle:CalendarEvent:editEvent }
    methods:  [GET, POST]

appBundle_add:
    path:     /calendrier/add
    defaults: { _controller: AppBundle:CalendarEvent:addEvent }
    methods:  [GET, POST]
