app:
    resource: '@AppBundle/Controller/'
    type: annotation

professeur_registration:
    path:  /register/professeur
    defaults: { _controller: AppBundle:RegistrationProfesseur:register }

etudiant_registration:
    path:  /register/etudiant
    defaults: { _controller: AppBundle:RegistrationEtudiant:register }

agent_administratif_registration:
    path:  /register/agent-administratif
    defaults: { _controller: AppBundle:RegistrationAgentAdministratif:register }

salle_add:
    path:  /salle/add
    defaults: { _controller: AppBundle:Salle:add }

etage_add:
    path: /etage/add
    defaults: { _controller: AppBundle:Etage:add }

batiment_add:
    path: /batiment/add
    defaults: { _controller: AppBundle:Batiment:add }

reservation_add:
    path: /reservation/add
    defaults: { _controller: AppBundle:Reservation:add }

fos_user_registration_confirmed:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /confirmed

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

#fos_user_registration_register:
 #   resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
  #  prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
